config/routes.rb
# frozen_string_literal: true

# == Route Map
#

# require 'resque/server'
require "sidekiq/web"
require "sidekiq_unique_jobs/web"

Rails.application.routes.draw do
  resources :tte_documents do
    member do
      get :status
      get :download
    end
  end
  resources :bpmn_spbes do
    member do
      get :tambah_catatan
      patch :simpan_catatan
      get :upload_file
      get :upload_file_laporan
    end
    collection do
      get :pilih
      get :filter_rekap
    end
  end
  resources :rencana_aksi_opds do
    collection do
      get :cetak
      get :filter_rekapitulasi
      get :cetak_rekapitulasi
      get :jumlah_rekapitulasi
      get :jumlah_perintah_walikota
      get :cetak_rekap_jumlah
      get :cetak_jumlah_perintah_walikota
    end
    member do
      patch :toggle_sasarans_is_perintah_walikota
    end
  end
  resources :program_unggulans do
    collection do
      get :asta_karya
      get :filter
      get :asta_cita
      get :filter_asta_cita
      get :nawa_bhakti
      get :filter_nawa_bhakti
    end
  end
  resources :kolabs do
    collection do
      get :opd_kolaborator
    end
  end
  resources :misis, path: "misi_kota" do
    collection do
      get :lists
    end
  end
  resources :visis, path: "visi_kota"
  resources :manrisks do
    collection do
      get :filter
      get :konteks_strategis
      get :identifikasi_strategis
      get :filter_identifikasi_strategis
    end
    member do
      get :filter_konteks_strategis
      get :edit_konteks_strategis
      post :simpan_konteks_strategis
    end
  end
  resources :realisasis
  resources :inovasi_masyarakats
  resources :anggota_tims
  resources :inovasi_tims do
    collection do
      get :new_internal
      get :new_non_pemerintah
    end
  end
  resources :mitras do
    collection do
      get :new_internal
      get :new_external_pemerintah
      get :new_external_non_pemerintah
      get :new_external_non_pemerintah_ogp
    end
  end
  resources :akar_masalahs do
    member do
      post :pilih_masalah
    end
  end
  resources :tim_kerja, only: [] do
    member do
      get :edit_dasar_hukum
      post :update_dasar_hukum
      delete :hapus_dasar_hukum
      get :edit_rincian_tugas
      post :update_rincian_tugas
      delete :hapus_rincian_tugas
    end
  end
  resources :kuncis
  resources :anggaran_sbks
  resources :asets
  resources :jenis_jabatans
  resources :jumlahs
  resources :data_dukungs
  resources :indikators_users do
    collection do
      get :indikator_by_jenis
      get :pelaksana_indikator
    end
  end
  resources :indikators do
    collection do
      post :import
      get :rpjp_makro
      get :rpjp_opd
      get :rpjmd_makro
      get :rkpd_makro
      get :rkpd_tujuan
      get :rkpd_sasaran
      get :rkpd_program
      get :iku_kota
      get :renja_opd
      post :item_renja_opd
      get :tujuan_renja_opd
      get :sasaran_renja_opd
      get :program_renja_opd
      get :kegiatan_renja_opd
      get :subkegiatan_renja_opd
      get :iku_opd
      get :iku_sakip
      get :cetak_iku_opd
      get :lppd_outcome
      get :lppd_output
      get :spm_outcome
      get :spm_output
      get :sdgs_outcome
      get :sdgs_output
      get :rb_outcome
      get :rb_output
      get :stunting_outcome
      get :stunting_output
      get :penanganan_tb_outcome
      get :penanganan_tb_output

      get :new_target_iku_sasaran
    end

    member do
      get :edit_target_iku
      patch :update_iku
      patch :update_realisasi
      delete :hide_iku
      delete :hide_iku_indikator_sasaran
      delete :hide_iku_sasaran
      get :edit_keterangan
      patch :update_keterangan
    end
  end
  resources :pindah_pohon_kinerjas, only: %i[show edit update]
  resources :permasalahan_opds
  resources :strategi_arah_kebijakans do
    collection do
      get :opd
    end
  end
  resources :jabatans do
    resources :kepegawaians do
      collection do
        get :edit_jumlah
        post :update_jumlah
      end
    end
  end
  resources :status_tombols
  resources :external_urls
  resources :reviews
  resources :kriteria
  resources :sub_kriteria
  resources :pelaksana do
    member do
      get :teman
      get :edit_role_tim
      post :update_role_tim
    end
    collection do
      patch :toggle_inovator
    end
  end
  resources :crosscuttings do
    member do
      get :edit_keterangan
      post :update_keterangan
    end
    collection do
      get :internal
      get :external
      get :external_pemerintah
      get :external_non_pemerintah
    end
  end
  resources :pohon_kinerja_opds do
    member do
      get :new_child
    end
    collection do
      get :cascading
    end
  end
  resources :tims
  # TODO: Refactor controller to resources
  resources :pohon_tematik do
    member do
      get :new_sub
      get :edit_sub_tematik
      get :pindah_sub_tematik
      patch :update_sub_tematik
      get :new_opd_tematik
      get :edit_opd_tematik
      patch :update_opd_tematik
      get :pindah_opd_tematik
      get :new_strategi_tematik
      get :new_strategi
      get :edit_strategi
      patch :update_strategi
      get :new_tactical_tematik
      get :new_tactical
      get :edit_tactical
      patch :update_tactical
      get :new_operational_tematik
      get :new_operational
      get :edit_operational
      patch :update_operational
      patch :pindah_pohon
      patch :terima
      get :tolak_strategi
      patch :tolak
      get :new_sub_sub
      get :edit_sub_sub
      patch :toggle_is_active
    end
    collection do
      post :create_sub_tema
      post :create_opd_tematik
      post :create_strategi_tematik
      post :create_strategi_tematik_baru
      post :create_tactical_tematik
      post :create_tactical_tematik_baru
      post :create_operational_tematik
      post :create_operational_tematik_baru
      post :create_sub_sub_tema
      get :filter
      get :get_tematik_opd
    end
  end
  resources :tematiks do
    collection do
      get :list_tematik_kota
      get :sub_tematiks
      post :sub
      get :new_sub
    end

    member do
      get :edit_sub
      post :sub
      get :rad_cetak
      patch :update_sub
      delete :sub
    end
  end
  resources :sub_sub_tematiks, only: %i[create update]
  resources :subdomains
  resources :opd_bidangs
  resources :periodes
  resources :tahuns
  resources :domains
  resources :kebutuhans
  resources :komentars do
    collection do
      get :komentar_pokin
    end
  end
  resources :spbe_rincians
  resources :spbes do
    collection do
      get :index_opd
      get :custom_tanggal_cetak
      get :cetak
      get :cetak_kota
    end
    member do
      get :edit_operational_opd
    end
  end
  resources :pagu_anggarans do
    get :new_batasan, on: :collection
    post :create_batasan, on: :collection
    get :edit_serapan, on: :collection
    post :simpan_serapan, on: :collection
    member do
      get :edit_batasan
      patch :update_batasan
    end
  end
  resources :indikator_sasarans do
    resources :manual_iks do
      member do
        get :overview
      end
    end
  end
  resources :sasaran_opds
  resources :tujuan_opds do
    collection do
      post :admin_filter
    end
  end
  resources :pohon_kinerja do
    member do
      get :transfer_pohon
      post :transfer
      get :panggil_teman
      post :simpan_teman
      get :daftar_temans
      get :daftar_strategi
      post :pasangkan
      get :daftar_linked_strategi
      post :set_clone
      get :pindah
      get :list_dibagikan
      get :new_tactical
      get :new_operational
    end
    collection do
      get :kota
      get :cascading
      get :opd
      get :asn
      post :admin_filter
      get :print
      get :excel_kota
      get :pdf_pokin_kota
      get :pdf_cascading_kota
      get :pdf_pokin_opd
      get :pdf_cascading_opd
      get :excel_opd
      get :rekap
      post :filter_rekap
      get :rekap_opd
      post :filter_rekap_opd
      get :clone_list_opd
      post :clone_pokin_opd
      post :clone_pokin_isu_strategis_opd
      post :clone_pokin_kota
      get :review_opd
      get :review_kota
      get :manual
      get :clone
      get :new_strategic
      get :list_pohon
    end
  end
  resources :strategi_opds
  resources :strategi_kota do
    member do
      get :bagikan_ke_opd
      post :pilih_opd
      get :list_strategi_opd
      post :hapus_bagikan_ke_opd
    end
  end
  resources :strategis do
    member do
      get :bagikan_pokin
      post :pilih_asn
      get :list_strategi_asn
      post :hapus_bagikan_ke_asn
      get :ganti_nip
      get :renaksi
    end
    collection do
      get :rekap_strategi
      get :pokin_list
    end
  end
  resources :isu_strategis_opds do
    collection do
      post :admin_filter
    end
    member do
      get :clone
    end
  end
  resources :isu_strategis_kota do
    member do
      get :list_strategi_kota
    end
  end
  # get "/gender", to: "genders#gender"
  # get "/gap_gender", to: "genders#gap_gender"
  # get "/laporan_gender", to: "genders#laporan_gender"
  # get "/pdf_gender/:id/:tahun", to: "genders#pdf_gender"
  resources :genders do
    collection do
      get :gender
      get :gap
      get :gbs
      get :laporan_gender
      get :laporan_gap
      get :laporan_gbs
      # get "pdf_gender/:id/:tahun", to: "genders#pdf_gender"
      # get "pdf_gap_gender/:id/:tahun", to: "genders#pdf_gap_gender"
    end

    member do
      get :pdf_gbs
      get :pdf_gap
      get :admin_edit
    end
  end
  resources :tujuans
  # get 'isu_dan_permasalahans/index'
  resources :renstra do
    collection do
      get :admin_renstra
      get :laporan
      get :renstra_cetak
      get :edit_indikator
      post :update_indikator
    end
    member do
      post :update_programs
      get :edit_realisasi
    end
  end

  resources :isu_dan_permasalahans, param: :kode_program do
    member do
      get :add_new
      post :add_isu_strategis
    end
  end

app/models/mitra.rb
# == Schema Information
#
# Table name: mitras
#
#  id                   :bigint           not null, primary key
#  jenis_mitra          :string
#  keterangan           :string
#  nama_kerjasama       :string
#  penjelasan_kerjasama :string
#  tahun_kerjasama      :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  crosscutting_id      :bigint           not null
#
# Indexes
#
#  index_mitras_on_crosscutting_id  (crosscutting_id)
#
# Foreign Keys
#
#  fk_rails_...  (crosscutting_id => crosscuttings.id)
#
class Mitra < ApplicationRecord
  belongs_to :crosscutting
end

app/controllers/mitras_controller.rb
class MitrasController < ApplicationController
  before_action :set_mitra, only: %i[show edit update destroy]
  layout false

  # GET /mitras or /mitras.json
  def index
    @mitras = Mitra.all
  end

  # GET /mitras/1 or /mitras/1.json
  def show; end

  # GET /mitras/new
  def new
    @mitra = Mitra.new
  end

  def new_internal
    render partial: 'mitra_internal_fields'
  end

  def new_external_pemerintah
    render partial: 'mitra_external_pemerintah_fields'
  end

  def new_external_non_pemerintah
    render partial: 'mitra_external_non_pemerintah_fields'
  end

  def new_external_non_pemerintah_ogp
    render partial: 'mitra_external_non_pemerintah_ogp_fields'
  end

  # GET /mitras/1/edit
  def edit; end

  # POST /mitras or /mitras.json
  def create
    @mitra = Mitra.new(mitra_params)

    respond_to do |format|
      if @mitra.save
        format.html { redirect_to mitra_url(@mitra), notice: "Mitra was successfully created." }
        format.json { render :show, status: :created, location: @mitra }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mitra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mitras/1 or /mitras/1.json
  def update
    respond_to do |format|
      if @mitra.update(mitra_params)
        format.html { redirect_to mitra_url(@mitra), notice: "Mitra was successfully updated." }
        format.json { render :show, status: :ok, location: @mitra }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mitra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mitras/1 or /mitras/1.json
  def destroy
    @mitra.destroy

    respond_to do |format|
      format.html { redirect_to mitras_url, notice: "Mitra was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_mitra
    @mitra = Mitra.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def mitra_params
    params.require(:mitra).permit(:jenis_mitra, :nama_kerjasama, :penjelasan_kerjasama, :tahun_kerjasama,
                                  :keterangan, :crosscutting_id)
  end
end

app/helpers/mitras_helper.rb
module MitrasHelper
end

app/views/mitras/_form.html.erb
<%= form_with(model: mitra) do |form| %>
  <% if mitra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mitra.errors.count, "error") %> prohibited this mitra from being saved:</h2>

      <ul>
        <% mitra.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div id="mitra-internal">
    <div class="field">
      <%= form.hidden_field :jenis_mitra, value: 'opd-internal' %>
      <%= form.label :tahun_kerjasama, { class: "form-label" } %>
      <%= form.select(:tahun_kerjasama, options_for_select(Tahun.pluck(:tahun), form.object.tahun_kerjasama), {},
                      { data: {"placeholder": "Pilih Tahun",
                               controller: 'dropdown',
                               dropdown_parent_value: '#mitra-internal'
      }}) %>
    </div>
    <div class="field">
      <%= form.label :nama_kerjasama, { class: "form-label" } %>
      <%= form.text_area :nama_kerjasama, { class: "form-control", placeholder: 'input nama kerjasama' } %>
    </div>
    <div class="field">
      <%= form.label :penjelasan_kerjasama, { class: "form-label" } %>
      <%= form.text_area :penjelasan_kerjasama, { class: "form-control", placeholder: 'input deskripsi kerjasama' } %>
    </div>
  </div>
<% end %>

app/views/mitras/_mitra_external_non_pemerintah_fields.html.erb
<div id="mitra-external-non-pemerintah">
  <div class="field">
    <%= hidden_field_tag "crosscutting[mitras_attributes][0][jenis_mitra]", 'non-pemerintah-external' %>
    <%= label_tag "crosscutting[mitras_attributes][0][tahun_kerjasama]", "Tahun Kerjasama", { class: "form-label" } %>
    <%= select_tag "crosscutting[mitras_attributes][0][tahun_kerjasama]", options_for_select(Tahun.pluck(:tahun), Date.today.year.to_s),
                   { data: {"placeholder": "Pilih Tahun",
                            controller: 'dropdown',
                            dropdown_parent_value: '#mitra-external-non-pemerintah'}} %>
  </div>
  <div class="field">
    <%= label_tag "crosscutting[mitras_attributes][0][nama_kerjasama]", "Nama Kerjasama", { class: "form-label" } %>
    <%= text_area_tag "crosscutting[mitras_attributes][0][nama_kerjasama]", "", class: "form-control", placeholder: 'input nama kerjasama' %>
  </div>
  <div class="field">
    <%= label_tag "crosscutting[mitras_attributes][0][penjelasan_kerjasama]", "Penjelasan Kerjasama", { class: "form-label" } %>
    <%= text_area_tag "crosscutting[mitras_attributes][0][penjelasan_kerjasama]", "", { class: "form-control", placeholder: 'input deskripsi kerjasama' } %>
  </div>
</div>

app/views/mitras/_mitra_external_non_pemerintah_ogp_fields.html.erb
<div id="mitra-external-non-pemerintah-ogp">
  <div class="field">
    <%= hidden_field_tag "crosscutting[mitras_attributes][1][jenis_mitra]", 'non-pemerintah-external-ogp' %>
    <%= label_tag "crosscutting[mitras_attributes][1][tahun_kerjasama]", "Tahun Kerjasama", { class: "form-label" } %>
    <%= select_tag "crosscutting[mitras_attributes][1][tahun_kerjasama]", options_for_select(Tahun.pluck(:tahun), Date.today.year.to_s),
                   { data: {"placeholder": "Pilih Tahun",
                            controller: 'dropdown',
                            dropdown_parent_value: '#mitra-external-non-pemerintah-ogp'}} %>
  </div>
  <div class="field">
    <%= label_tag "crosscutting[mitras_attributes][1][nama_kerjasama]", "Nama Kerjasama", { class: "form-label" } %>
    <%= text_area_tag "crosscutting[mitras_attributes][1][nama_kerjasama]", "", class: "form-control", placeholder: 'input nama kerjasama' %>
  </div>
  <div class="field">
    <%= label_tag "crosscutting[mitras_attributes][1][penjelasan_kerjasama]", "Penjelasan Kerjasama", { class: "form-label" } %>
    <%= text_area_tag "crosscutting[mitras_attributes][1][penjelasan_kerjasama]", "", { class: "form-control", placeholder: 'input deskripsi kerjasama' } %>
  </div>
</div>

app/views/mitras/_mitra_external_pemerintah_fields.html.erb
<div id="mitra-external-pemerintah">
  <div class="field">
    <%= hidden_field_tag "crosscutting[mitras_attributes][0][jenis_mitra]", 'pemerintah-external' %>
    <%= label_tag "crosscutting[mitras_attributes][0][tahun_kerjasama]", "Tahun Kerjasama", { class: "form-label" } %>
    <%= select_tag "crosscutting[mitras_attributes][0][tahun_kerjasama]", options_for_select(Tahun.pluck(:tahun), Date.today.year.to_s),
                   { data: {"placeholder": "Pilih Tahun",
                            controller: 'dropdown',
                            dropdown_parent_value: '#mitra-external-pemerintah'}} %>
  </div>
  <div class="field">
    <%= label_tag "crosscutting[mitras_attributes][0][nama_kerjasama]", "Nama Kerjasama", { class: "form-label" } %>
    <%= text_area_tag "crosscutting[mitras_attributes][0][nama_kerjasama]", "", class: "form-control", placeholder: 'input nama kerjasama' %>
  </div>
  <div class="field">
    <%= label_tag "crosscutting[mitras_attributes][0][penjelasan_kerjasama]", "Penjelasan Kerjasama", { class: "form-label" } %>
    <%= text_area_tag "crosscutting[mitras_attributes][0][penjelasan_kerjasama]", "", { class: "form-control", placeholder: 'input deskripsi kerjasama' } %>
  </div>
</div>

app/views/mitras/_mitra_internal_fields.html.erb
<div id="mitra-internal">
  <div class="field">
    <%= hidden_field_tag "crosscutting[mitras_attributes][0][jenis_mitra]", 'opd-internal' %>
    <%= label_tag "crosscutting[mitras_attributes][0][tahun_kerjasama]", "Tahun Kerjasama", { class: "form-label" } %>
    <%= select_tag "crosscutting[mitras_attributes][0][tahun_kerjasama]", options_for_select(Tahun.pluck(:tahun), Date.today.year.to_s),
                   { data: {"placeholder": "Pilih Tahun",
                            controller: 'dropdown',
                            dropdown_parent_value: '#mitra-internal'}} %>
  </div>
  <div class="field">
    <%= label_tag "crosscutting[mitras_attributes][0][nama_kerjasama]", "Nama Kerjasama", { class: "form-label" } %>
    <%= text_area_tag "crosscutting[mitras_attributes][0][nama_kerjasama]", "", class: "form-control", placeholder: 'input nama kerjasama' %>
  </div>
  <div class="field">
    <%= label_tag "crosscutting[mitras_attributes][0][penjelasan_kerjasama]", "Penjelasan Kerjasama", { class: "form-label" } %>
    <%= text_area_tag "crosscutting[mitras_attributes][0][penjelasan_kerjasama]", "", { class: "form-control", placeholder: 'input deskripsi kerjasama' } %>
  </div>
</div>

app/views/mitras/edit.html.erb
<h1>Editing Mitra</h1>

<%= render 'form', mitra: @mitra %>

<%= link_to 'Show', @mitra %> |
<%= link_to 'Back', mitras_path %>

app/views/mitras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mitras</h1>

<table>
  <thead>
    <tr>
      <th>Jenis mitra</th>
      <th>Nama kerjasama</th>
      <th>Penjelasan kerjasama</th>
      <th>Tahun kerjasama</th>
      <th>Keterangan</th>
      <th>Crosscutting</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mitras.each do |mitra| %>
      <tr>
        <td><%= mitra.jenis_mitra %></td>
        <td><%= mitra.nama_kerjasama %></td>
        <td><%= mitra.penjelasan_kerjasama %></td>
        <td><%= mitra.tahun_kerjasama %></td>
        <td><%= mitra.keterangan %></td>
        <td><%= mitra.crosscutting_id %></td>
        <td><%= link_to 'Show', mitra %></td>
        <td><%= link_to 'Edit', edit_mitra_path(mitra) %></td>
        <td><%= link_to 'Destroy', mitra, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mitra', new_mitra_path %>

app/views/mitras/new.html.erb
<%= render 'form', mitra: @mitra %>

app/views/mitras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Jenis mitra:</strong>
  <%= @mitra.jenis_mitra %>
</p>

<p>
  <strong>Nama kerjasama:</strong>
  <%= @mitra.nama_kerjasama %>
</p>

<p>
  <strong>Penjelasan kerjasama:</strong>
  <%= @mitra.penjelasan_kerjasama %>
</p>

<p>
  <strong>Tahun kerjasama:</strong>
  <%= @mitra.tahun_kerjasama %>
</p>

<p>
  <strong>Keterangan:</strong>
  <%= @mitra.keterangan %>
</p>

<p>
  <strong>Crosscutting:</strong>
  <%= @mitra.crosscutting_id %>
</p>

<%= link_to 'Edit', edit_mitra_path(@mitra) %> |
<%= link_to 'Back', mitras_path %>