config/routes.rb
# frozen_string_literal: true

# == Route Map
#

# require 'resque/server'
require "sidekiq/web"
require "sidekiq_unique_jobs/web"

Rails.application.routes.draw do
  resources :tte_documents do
    member do
      get :status
      get :download
    end
  end
  resources :bpmn_spbes do
    member do
      get :tambah_catatan
      patch :simpan_catatan
      get :upload_file
      get :upload_file_laporan
    end
    collection do
      get :pilih
      get :filter_rekap
    end
  end
  resources :rencana_aksi_opds do
    collection do
      get :cetak
      get :filter_rekapitulasi
      get :cetak_rekapitulasi
      get :jumlah_rekapitulasi
      get :jumlah_perintah_walikota
      get :cetak_rekap_jumlah
      get :cetak_jumlah_perintah_walikota
    end
    member do
      patch :toggle_sasarans_is_perintah_walikota
    end
  end
  resources :program_unggulans do
    collection do
      get :asta_karya
      get :filter
      get :asta_cita
      get :filter_asta_cita
      get :nawa_bhakti
      get :filter_nawa_bhakti
    end
  end
  resources :kolabs do
    collection do
      get :opd_kolaborator
    end
  end
  resources :misis, path: "misi_kota" do
    collection do
      get :lists
    end
  end
  resources :visis, path: "visi_kota"
  resources :manrisks do
    collection do
      get :filter
      get :konteks_strategis
      get :identifikasi_strategis
      get :filter_identifikasi_strategis
    end
    member do
      get :filter_konteks_strategis
      get :edit_konteks_strategis
      post :simpan_konteks_strategis
    end
  end
  resources :realisasis
  resources :inovasi_masyarakats
  resources :anggota_tims
  resources :inovasi_tims do
    collection do
      get :new_internal
      get :new_non_pemerintah
    end
  end
  resources :mitras do
    collection do
      get :new_internal
      get :new_external_pemerintah
      get :new_external_non_pemerintah
      get :new_external_non_pemerintah_ogp
    end
  end
  resources :akar_masalahs do
    member do
      post :pilih_masalah
    end
  end
  resources :tim_kerja, only: [] do
    member do
      get :edit_dasar_hukum
      post :update_dasar_hukum
      delete :hapus_dasar_hukum
      get :edit_rincian_tugas
      post :update_rincian_tugas
      delete :hapus_rincian_tugas
    end
  end
  resources :kuncis
  resources :anggaran_sbks
  resources :asets
  resources :jenis_jabatans
  resources :jumlahs
  resources :data_dukungs
  resources :indikators_users do
    collection do
      get :indikator_by_jenis
      get :pelaksana_indikator
    end
  end
  resources :indikators do
    collection do
      post :import
      get :rpjp_makro
      get :rpjp_opd
      get :rpjmd_makro
      get :rkpd_makro
      get :rkpd_tujuan
      get :rkpd_sasaran
      get :rkpd_program
      get :iku_kota
      get :renja_opd
      post :item_renja_opd
      get :tujuan_renja_opd
      get :sasaran_renja_opd
      get :program_renja_opd
      get :kegiatan_renja_opd
      get :subkegiatan_renja_opd
      get :iku_opd
      get :iku_sakip
      get :cetak_iku_opd
      get :lppd_outcome
      get :lppd_output
      get :spm_outcome
      get :spm_output
      get :sdgs_outcome
      get :sdgs_output
      get :rb_outcome
      get :rb_output
      get :stunting_outcome
      get :stunting_output
      get :penanganan_tb_outcome
      get :penanganan_tb_output

      get :new_target_iku_sasaran
    end

    member do
      get :edit_target_iku
      patch :update_iku
      patch :update_realisasi
      delete :hide_iku
      delete :hide_iku_indikator_sasaran
      delete :hide_iku_sasaran
      get :edit_keterangan
      patch :update_keterangan
    end
  end
  resources :pindah_pohon_kinerjas, only: %i[show edit update]
  resources :permasalahan_opds
  resources :strategi_arah_kebijakans do
    collection do
      get :opd
    end
  end
  resources :jabatans do
    resources :kepegawaians do
      collection do
        get :edit_jumlah
        post :update_jumlah
      end
    end
  end
  resources :status_tombols
  resources :external_urls
  resources :reviews
  resources :kriteria
  resources :sub_kriteria
  resources :pelaksana do
    member do
      get :teman
      get :edit_role_tim
      post :update_role_tim
    end
    collection do
      patch :toggle_inovator
    end
  end
  resources :crosscuttings do
    member do
      get :edit_keterangan
      post :update_keterangan
    end
    collection do
      get :internal
      get :external
      get :external_pemerintah
      get :external_non_pemerintah
    end
  end
  resources :pohon_kinerja_opds do
    member do
      get :new_child
    end
    collection do
      get :cascading
    end
  end
  resources :tims
  # TODO: Refactor controller to resources
  resources :pohon_tematik do
    member do
      get :new_sub
      get :edit_sub_tematik
      get :pindah_sub_tematik
      patch :update_sub_tematik
      get :new_opd_tematik
      get :edit_opd_tematik
      patch :update_opd_tematik
      get :pindah_opd_tematik
      get :new_strategi_tematik
      get :new_strategi
      get :edit_strategi
      patch :update_strategi
      get :new_tactical_tematik
      get :new_tactical
      get :edit_tactical
      patch :update_tactical
      get :new_operational_tematik
      get :new_operational
      get :edit_operational
      patch :update_operational
      patch :pindah_pohon
      patch :terima
      get :tolak_strategi
      patch :tolak
      get :new_sub_sub
      get :edit_sub_sub
      patch :toggle_is_active
    end
    collection do
      post :create_sub_tema
      post :create_opd_tematik
      post :create_strategi_tematik
      post :create_strategi_tematik_baru
      post :create_tactical_tematik
      post :create_tactical_tematik_baru
      post :create_operational_tematik
      post :create_operational_tematik_baru
      post :create_sub_sub_tema
      get :filter
      get :get_tematik_opd
    end
  end
  resources :tematiks do
    collection do
      get :list_tematik_kota
      get :sub_tematiks
      post :sub
      get :new_sub
    end

    member do
      get :edit_sub
      post :sub
      get :rad_cetak
      patch :update_sub
      delete :sub
    end
  end
  resources :sub_sub_tematiks, only: %i[create update]
  resources :subdomains
  resources :opd_bidangs
  resources :periodes
  resources :tahuns
  resources :domains
  resources :kebutuhans
  resources :komentars do
    collection do
      get :komentar_pokin
    end
  end
  resources :spbe_rincians
  resources :spbes do
    collection do
      get :index_opd
      get :custom_tanggal_cetak
      get :cetak
      get :cetak_kota
    end
    member do
      get :edit_operational_opd
    end
  end
  resources :pagu_anggarans do
    get :new_batasan, on: :collection
    post :create_batasan, on: :collection
    get :edit_serapan, on: :collection
    post :simpan_serapan, on: :collection
    member do
      get :edit_batasan
      patch :update_batasan
    end
  end
  resources :indikator_sasarans do
    resources :manual_iks do
      member do
        get :overview
      end
    end
  end
  resources :sasaran_opds
  resources :tujuan_opds do
    collection do
      post :admin_filter
    end
  end
  resources :pohon_kinerja do
    member do
      get :transfer_pohon
      post :transfer
      get :panggil_teman
      post :simpan_teman
      get :daftar_temans
      get :daftar_strategi
      post :pasangkan
      get :daftar_linked_strategi
      post :set_clone
      get :pindah
      get :list_dibagikan
      get :new_tactical
      get :new_operational
    end
    collection do
      get :kota
      get :cascading
      get :opd
      get :asn
      post :admin_filter
      get :print
      get :excel_kota
      get :pdf_pokin_kota
      get :pdf_cascading_kota
      get :pdf_pokin_opd
      get :pdf_cascading_opd
      get :excel_opd
      get :rekap
      post :filter_rekap
      get :rekap_opd
      post :filter_rekap_opd
      get :clone_list_opd
      post :clone_pokin_opd
      post :clone_pokin_isu_strategis_opd
      post :clone_pokin_kota
      get :review_opd
      get :review_kota
      get :manual
      get :clone
      get :new_strategic
      get :list_pohon
    end
  end
  resources :strategi_opds
  resources :strategi_kota do
    member do
      get :bagikan_ke_opd
      post :pilih_opd
      get :list_strategi_opd
      post :hapus_bagikan_ke_opd
    end
  end
  resources :strategis do
    member do
      get :bagikan_pokin
      post :pilih_asn
      get :list_strategi_asn
      post :hapus_bagikan_ke_asn
      get :ganti_nip
      get :renaksi
    end
    collection do
      get :rekap_strategi
      get :pokin_list
    end
  end
  resources :isu_strategis_opds do
    collection do
      post :admin_filter
    end
    member do
      get :clone
    end
  end
  resources :isu_strategis_kota do
    member do
      get :list_strategi_kota
    end
  end
  # get "/gender", to: "genders#gender"
  # get "/gap_gender", to: "genders#gap_gender"
  # get "/laporan_gender", to: "genders#laporan_gender"
  # get "/pdf_gender/:id/:tahun", to: "genders#pdf_gender"
  resources :genders do
    collection do
      get :gender
      get :gap
      get :gbs
      get :laporan_gender
      get :laporan_gap
      get :laporan_gbs
      # get "pdf_gender/:id/:tahun", to: "genders#pdf_gender"
      # get "pdf_gap_gender/:id/:tahun", to: "genders#pdf_gap_gender"
    end

    member do
      get :pdf_gbs
      get :pdf_gap
      get :admin_edit
    end
  end
  resources :tujuans
  # get 'isu_dan_permasalahans/index'
  resources :renstra do
    collection do
      get :admin_renstra
      get :laporan
      get :renstra_cetak
      get :edit_indikator
      post :update_indikator
    end
    member do
      post :update_programs
      get :edit_realisasi
    end
  end

  resources :isu_dan_permasalahans, param: :kode_program do
    member do
      get :add_new
      post :add_isu_strategis
    end
  end

app/controllers/rincian_belanja_controller.rb
class RincianBelanjaController < ApplicationController
  before_action :set_user
  before_action :set_tahun

  def index
    kak = KakQueries.new(opd: @user.opd, tahun: @tahun, user: @user)
    @subkegiatan_sasarans = kak.pk_sasarans
  end

  def index_atasan
    @subkegiatan_sasarans = @user.program_sasarans_tahun(@tahun)
  end

  def show
    @sasaran = Sasaran.find(params[:id])
  end

  def edit
    @sasaran = Sasaran.find(params[:id])
    @dikunci = @sasaran.kuncian('rankir2')
  end

  def kunci_anggaran
    @sasaran = Sasaran.find(params[:id])
    render layout: false
  end

  def kunci_keterangan
    @sasaran = Sasaran.find(params[:id])
    @jenis = params[:jenis]
    @total = params[:total]
    render layout: false
  end

  def simpan_kunci
    @sasaran = Sasaran.find(params[:id])
    @jenis = params[:jenis]
    @total = params[:total]
    keterangan = params[:keterangan]
    status_anggaran = "dikunci"
    dikunci_oleh = current_user.nik

    kunci = Kunci.new(jenis: @jenis,
                      status_kunci: status_anggaran,
                      kunciable_id: @sasaran.id,
                      kunciable_type: @sasaran.class.name,
                      keterangan: keterangan,
                      dikunci_oleh: dikunci_oleh)
    if kunci.save
      anggaran = { jenis: @jenis, total: @total, keterangan: keterangan, status: kunci.status_kunci }

      render json: { resText: "Anggaran #{@jenis} dikunci",
                     html_content: html_content({ anggaran: anggaran },
                                                partial: 'rincian_belanja/anggaran') }.to_json,
             status: :ok
    else
      render json: { resText: 'Terjadi kesalahan',
                     html_content: error_content({ sasaran: @sasaran  },
                                                 partial: 'rincian_belanja/form_kunci_anggaran') }.to_json,
             status: :unprocessable_entity
    end
  end

  def show_subkegiatan
    @subkegiatan = ProgramKegiatan.find(params[:id])
    @sasarans = @subkegiatan.sasarans_subkegiatan(@tahun)
    @rekening_sub = @subkegiatan.rekening_belanja(@tahun)
  end

  def edit_rankir_gelondong
    @sasaran = Sasaran.find(params[:id])
    @tahapans = @sasaran.tahapans.includes(%i[anggarans])
    @dikunci = @sasaran.kuncian('rankir1')
  end

  def edit_penetapan
    @sasaran = Sasaran.find(params[:id])
    @tahapans = @sasaran.tahapans.includes(%i[anggarans])
    @dikunci = @sasaran.kuncian('penetapan')
  end

  private

  def set_user
    @user = current_user
  end

  def set_tahun
    @tahun = cookies[:tahun]
  end
end

app/helpers/rincian_belanja_helper.rb
module RincianBelanjaHelper
  def link_edit_anggaran(anggaran, hitung)
    if hitung.deskripsi.downcase.include?('lain_lain')
      edit_lain_lain_anggaran_perhitungan_path(anggaran, hitung)
    elsif hitung.spesifikasi.include?('Belanja Gaji')
      edit_gaji_anggaran_perhitungan_path(anggaran, hitung)
    else
      edit_anggaran_perhitungan_path(anggaran, hitung)
    end
  end

  def uraian_rincian_anggaran(hitung)
    tahun = hitung.tahun
    spesifikasi = hitung.spesifikasi
    uraian = if hitung.deskripsi.downcase.include?('lain_lain') || hitung.spesifikasi.include?('Belanja Gaji')
               hitung.deskripsi
             else
               hitung.uraian_barang
             end
    "#{uraian} <br/> #{spesifikasi} <br/> - #{tahun}".html_safe
  end

  def spesifikasi_anggaran(kode_barang, tahun, jenis_barang)
    # update using delgate method polymorphic
    Search::AllAnggaran.find_by(kode_barang: kode_barang,
                                tahun: tahun,
                                searchable_type: jenis_barang)
                       .spesifikasi
  rescue NoMethodError
    'Tidak Ditemukan'
  end

  def anggaran_gaji?(anggaran)
    anggaran.include?("gaji") or
      anggaran.include?("tunjangan") or
      anggaran.include?("penghasilan") or
      anggaran.include?("honor") or
      anggaran.include?("iuran") or
      anggaran.include?("jaminan") or
      anggaran.include?("retribusi") or
      anggaran.include?("pengelolaan") or
      anggaran.include?("terduga") or
      anggaran.include?("jasa")
  end
end

app/views/rincian_belanja/_anggaran.html.erb
<tr data-controller="row">
  <td class="text-gray-900"><%= anggaran[:jenis].to_s.titleize %></td>
  <td class="text-gray-900">Rp. <%= number_with_delimiter(anggaran[:total]) %></td>
  <td class="text-gray-900"><%= anggaran[:keterangan] %></td>
  <td class="text-center" style="width: 150px;">
    <% if anggaran[:status] == 'dikunci' %>
      <button class="btn btn-sm btn-outline-primary" disabled>
        <span class="fas fa-lock me-2"></span>
        Anggaran Selesai
      </button>
    <% else %>
      <%= render(EditRowButtonComponent.new(title: 'Anggaran Selesai',path: kunci_keterangan_rincian_belanja_path(@sasaran, jenis: anggaran[:jenis], total: anggaran[:total]), icon: 'fas fa-key')) %>
    <% end %>
  </td>
</tr>

app/views/rincian_belanja/_form_kunci_anggaran.html.erb
<%= form_with url: simpan_kunci_rincian_belanja_path(sasaran),
              local: false,
              id: dom_id(sasaran, 'form'),
              data: {
                action: 'ajax:complete->row#processAjax',
              } do |form| %>
  <td class="text-gray-900">
    <%= form.hidden_field :jenis, form: dom_id(sasaran, 'form'), value: @jenis %>
    <%= form.hidden_field :total, form: dom_id(sasaran, 'form'), value: @total %>
    <%= @jenis.titleize %>
  </td>
  <td class="text-gray-900">Rp. <%= number_with_delimiter(@total) %></td>
  <td class="text-gray-900">
    <%= form.text_area :keterangan, { class: "form-control",  cols: 5, rows: 4,required: true, form: dom_id(sasaran, 'form'), placeholder: 'tuliskan alasan penguncian anggaran' } %>
  </td>
  <td class="text-center" style="width: 150px;">
    <div class="d-grid gap-2">
      <%= form.submit 'Kunci', class: 'btn btn-sm', style: 'margin-top: 0 !important;',
         form: dom_id(sasaran, 'form') %>
      <button class="btn btn-sm btn-outline-danger" data-action="row#batal">Batal</button>
    </div>
  </td>
<% end %>

app/views/rincian_belanja/_modal.html.erb
<div class="modal fade " id="form-renaksi" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="form-renaksi-title">Form Rencana Aksi</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="form-renaksi-body">
        ...
      </div>
    </div>
  </div>
</div>

app/views/rincian_belanja/_modal_perhitungans.html.erb
<div class="modal fade " id="form-perhitungan" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered  modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="form-perhitungan-title">Form Anggaran</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="form-perhitungan-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger w-100 mb-3" data-bs-dismiss="modal" aria-label="Close">Batal</button>
      </div>
    </div>
  </div>
</div>

app/views/rincian_belanja/edit_rankir_gelondong.html.erb
<%= content_for :html_title, "Edit Pagu Global" %>
<%= content_for :navigation do %>
  <li class="breadcrumb-item">Perencanaan</li>
  <li class="breadcrumb-item">Rincian Belanja</li>
  <li class="breadcrumb-item active" aria-current="page">Edit Pagu Global</li>
<% end %>
<% content_for :view_utama do %>
  <div class="px-3">
    <% if @dikunci %>
      <div class="card border-2 shadow mb-3">
        <div class="card-body">
          <h5>Status Anggaran
            <span class="badge bg-primary p-2">
              <span class="fas fa-lock me-2"></span>
              <%= @dikunci&.status_kunci.titleize %>
            </span>
          </h5>
          <hr />
          <div class="d-grid gap-2">
            <div class="keterangan_kunci">
              Keterangan: <%= @dikunci&.keterangan.titleize %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="card border-2 shadow mb-1">
      <div class="card-header">
        <div class="row align-items-center">
          <table class="table align-items-center">
            <thead>
              <tr>
                <th class="border text-center" scope="col" colspan="2"></th>
                <th class="border text-center" scope="col">Indikator</th>
                <th class="border text-center" scope="col">Target</th>
                <th class="border text-center" scope="col">Satuan</th>
              </tr>
            </thead>
            <tbody>
              <% indikator_sub = @sasaran.program_kegiatan&.indikator_subkegiatan_tahun(@tahun, @kode_opd) %>
              <tr class="table-info">
                <th class="border fw-bolder text-gray-900">Subkegiatan:</th>
                <td class="border text-wrap"><%= @sasaran.subkegiatan %></td>
                <td class="border text-wrap"><%= indikator_sub&.dig(:indikator) %></td>
                <td class="border text-wrap"><%= indikator_sub&.dig(:target) %></td>
                <td class="border text-wrap"><%= indikator_sub&.dig(:satuan) %></td>
              </tr>
              <% indikator = @sasaran.indikator_sasarans.first %>
              <tr>
                <th class="border fw-bolder text-gray-900">Rencana Kinerja</th>
                <td class="border text-wrap" rowspan="<%= @sasaran.indikator_sasarans.count  %>"><%= @sasaran.sasaran_kinerja %></td>
                <td class="border text-wrap"><%= indikator&.indikator_kinerja %></td>
                <td class="border text-wrap"><%= indikator&.target %></td>
                <td class="border text-wrap"><%= indikator&.satuan %></td>
              </tr>
              <% @sasaran.indikator_sasarans.drop(1).each do |indikator_s| %>
                <tr>
                  <td class="border text-wrap"><%= indikator_s.indikator_kinerja %></td>
                  <td class="border text-wrap"><%= indikator_s.target %></td>
                  <td class="border text-wrap"><%= indikator_s.satuan %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <% @tahapans.each do |tahapan| %>
      <div class="card border-2 shadow mb-1">
        <div class="card-header">
          <div class="row align-items-center">
            <p>Tahapan <%= ": #{tahapan.urutan} #{tahapan.tahapan_kerja}" %></p>
          </div>
        </div>
        <div class="card-body">
          <div class="anggaran">
            <% unless @dikunci&.status_kunci == 'dikunci' %>
              <%= link_to 'Tambah Rekening', new_sasaran_tahapan_anggaran_path(@sasaran, tahapan),
                          remote: true, data: { 'bs-toggle': 'modal', 'bs-target': "#form-perhitungan"},
                          class: "ml-5 mb-3 btn btn-outline-success" %>
              <%= link_to 'Tambah Rincian', new_sasaran_tahapan_anggaran_path(@sasaran, tahapan, level: 1),
                          remote: true, data: { 'bs-toggle': 'modal', 'bs-target': "#form-perhitungan"},
                          class: "ml-5 mb-3 btn btn-outline-success" %>
            <% end %>
            <table id="detail-anggaran">
              <thead>
                <tr>
                  <th class="text-center">Kode Rekening</th>
                  <th class="text-center">Uraian</th>
                  <th class="text-center">Rankir-1</th>
                  <th class="text-center">Rankir-2</th>
                  <th class="text-center">Aksi</th>
                </tr>
              </thead>
              <tbody>
                <% tahapan.grand_parent_anggaran.each do |rekening, anggarans| %>
                  <tr class="level-0 bg-gray-700 text-white">
                    <td class="text-white"><%= rekening %></td>
                    <td><%= find_rekening(rekening)&.jenis_rekening %></td>
                    <td class="uang text-end pe-2" id="<%= rekening %>" >Rp. <%= number_with_delimiter(tahapan.jumlah_grand_parent_penetapan(rekening)) %></td>
                    <td class="uang text-end pe-2">Rp. <%= number_with_delimiter(tahapan.jumlah_grand_parent(rekening)) %></td>
                    <td></td>
                  </tr>
                  <% anggarans.each do |anggaran| %>
                    <tr class="level-0 <%= 'higlighted' if anggaran.pagu_rankir_1.present? %>" data-controller="editable-table" >
                      <td><%= rekening_anggaran(anggaran.kode_rek) %> </td>
                      <td class="text-wrap">
                        <%= anggaran.uraian %>

                        <div class="d-flex align-items-center gap-2 mt-5">
                          <%= link_to new_tagging_anggaran_path(anggaran),
                                      remote: true,
                                      data: {
                                        controller: 'form-modal',
                                        action: 'ajax:complete->form-modal#success:prevent',
                                        bs_toggle: 'modal',
                                        bs_target: '#form-modal'
                                      },
                                      class: 'btn btn-sm btn-outline-primary' do %>
                            <i class="fas fa-plus me-2"></i>
                            <span>tagging</span>
                          <% end %>
                          <div class="selected-tags d-flex flex-wrap gap-1" id="<%= dom_id(anggaran, 'tagging') %>">
                            <%= render collection: anggaran.tagging_anggarans, partial: 'tagging_anggarans/tagging_anggaran', as: :tagging_anggaran  %>
                          </div>
                        </div>
                      </td>
                      <td class="text-end pe-2" data-editable-table-target="penetapan" width="170">Rp. <%= number_with_delimiter(anggaran.anggaran_rankir_1) %></td>
                      <td class="d-none text-end pe-2" data-editable-table-target="form" width="170"></td>
                      <td class="text-end pe-2" data-editable-table-target="anggaran">Rp. <%= number_with_delimiter(anggaran.jumlah) %></td>
                      <td class="text-center bg-white">
                        <% unless @dikunci&.status_kunci == 'dikunci' %>
                          <% if anggaran.pagu_rankir_1.present? %>
                            <%= link_to edit_pagu_anggaran_path(
                              anggaran.pagu_rankir_1,
                              anggaran: anggaran.id,
                              kode_belanja: rekening,
                              kode_sub_belanja: rekening_anggaran(anggaran.kode_rek),
                              jenis: "RankirGelondong",
                              sub_jenis: "SubBelanja",
                              tahun: @sasaran.tahun
                            ),
                                        remote: true, class: 'btn btn-outline-info',
                                        data: { action: 'editable-table#appendForm',
                                          editable_table_target: 'edit'
                                        } do %>
                              <span class="fas fa-pencil"></span>
                              <span>Edit Anggarans</span>
                            <% end %>
                          <% else %>
                            <%= link_to new_pagu_anggaran_path(
                              anggaran: anggaran.id,
                              kode_belanja: rekening,
                              kode_sub_belanja: rekening_anggaran(anggaran.kode_rek),
                              jenis: "RankirGelondong",
                              sub_jenis: "SubBelanja",
                              tahun: @sasaran.tahun
                            ),
                                        remote: true, class: 'btn btn-outline-info',
                                        data: { action: 'editable-table#appendForm',
                                          editable_table_target: 'edit'
                                        } do %>
                              <span class="fas fa-pencil"></span>
                              <span>Edit Anggaran</span>
                            <% end %>
                          <% end %>
                          <button class="d-none btn btn-tertiary" data-editable-table-target="simpan" data-action="editable-table#simpan">Simpan</button>
                          <button class="d-none btn btn-outline-danger" data-editable-table-target="cancel" data-action="editable-table#cancelForm">Batal</button>
                          <%= link_to "Hapus Anggaran", sasaran_tahapan_anggaran_path(@sasaran, tahapan, anggaran), method: :delete, data: {confirm_swal: "Hapus Anggaran #{anggaran.uraian}", editable_table_target: 'hapus'}, class: "btn btn-outline-danger me-2"  %>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
              <tfoot>
                <tr>
                  <td colspan="2">Jumlah Anggaran Tahapan :</td>
                  <td class="text-end" id="totalPenetapan">Rp. <%= number_with_delimiter(tahapan.anggaran_tahapan_rankir_1) %></td>
                  <td class="text-end">Rp. <%= number_with_delimiter(tahapan.anggaran_tahapan) %></td>
                  <td></td>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <!-- SECTION - Table Anggaran -->
  <!-- !SECTION - End Table Anggaran -->
  <%= render 'shared/modal_template', modal_name: 'anggaran' %>
  <%= render 'modal_perhitungans' %>

<% end %>

app/views/rincian_belanja/kunci_anggaran.html.erb
<div class="crosscutting-title">
  <h5>Sasaran : <%= @sasaran.sasaran_kinerja %></h5>
</div>
<div class="kunci-anggaran-body my-3" data-controller="form-modal">
  <div class="anggaran" data-form-modal-target="prevHtml">
    <table class="table table-bordered mb-3">
      <thead>
        <th class="text-start">Jenis Anggaran</th>
        <th class="text-start">Jumlah</th>
        <th class="text-wrap text-start">Keterangan</th>
        <th class="text-center">Action</th>
      </thead>
      <tbody>
        <%= render partial: 'anggaran', collection: @sasaran.seluruh_anggaran, as: :anggaran || '-' %>
      </tbody>
    </table>
  </div>
</div>

app/views/rincian_belanja/kunci_keterangan.html.erb
<tr data-controller="row" class="kuncian">
  <%= render 'rincian_belanja/form_kunci_anggaran', sasaran: @sasaran %>
</tr>