config/routes.rb
# frozen_string_literal: true

# == Route Map
#

# require 'resque/server'
require "sidekiq/web"
require "sidekiq_unique_jobs/web"

Rails.application.routes.draw do
  resources :tte_documents do
    member do
      get :status
      get :download
    end
  end
  resources :bpmn_spbes do
    member do
      get :tambah_catatan
      patch :simpan_catatan
      get :upload_file
      get :upload_file_laporan
    end
    collection do
      get :pilih
      get :filter_rekap
    end
  end
  resources :rencana_aksi_opds do
    collection do
      get :cetak
      get :filter_rekapitulasi
      get :cetak_rekapitulasi
      get :jumlah_rekapitulasi
      get :jumlah_perintah_walikota
      get :cetak_rekap_jumlah
      get :cetak_jumlah_perintah_walikota
    end
    member do
      patch :toggle_sasarans_is_perintah_walikota
    end
  end
  resources :program_unggulans do
    collection do
      get :asta_karya
      get :filter
      get :asta_cita
      get :filter_asta_cita
      get :nawa_bhakti
      get :filter_nawa_bhakti
    end
  end
  resources :kolabs do
    collection do
      get :opd_kolaborator
    end
  end
  resources :misis, path: "misi_kota" do
    collection do
      get :lists
    end
  end
  resources :visis, path: "visi_kota"
  resources :manrisks do
    collection do
      get :filter
      get :konteks_strategis
      get :identifikasi_strategis
      get :filter_identifikasi_strategis
    end
    member do
      get :filter_konteks_strategis
      get :edit_konteks_strategis
      post :simpan_konteks_strategis
    end
  end
  resources :realisasis
  resources :inovasi_masyarakats
  resources :anggota_tims
  resources :inovasi_tims do
    collection do
      get :new_internal
      get :new_non_pemerintah
    end
  end
  resources :mitras do
    collection do
      get :new_internal
      get :new_external_pemerintah
      get :new_external_non_pemerintah
      get :new_external_non_pemerintah_ogp
    end
  end
  resources :akar_masalahs do
    member do
      post :pilih_masalah
    end
  end
  resources :tim_kerja, only: [] do
    member do
      get :edit_dasar_hukum
      post :update_dasar_hukum
      delete :hapus_dasar_hukum
      get :edit_rincian_tugas
      post :update_rincian_tugas
      delete :hapus_rincian_tugas
    end
  end
  resources :kuncis
  resources :anggaran_sbks
  resources :asets
  resources :jenis_jabatans
  resources :jumlahs
  resources :data_dukungs
  resources :indikators_users do
    collection do
      get :indikator_by_jenis
      get :pelaksana_indikator
    end
  end
  resources :indikators do
    collection do
      post :import
      get :rpjp_makro
      get :rpjp_opd
      get :rpjmd_makro
      get :rkpd_makro
      get :rkpd_tujuan
      get :rkpd_sasaran
      get :rkpd_program
      get :iku_kota
      get :renja_opd
      post :item_renja_opd
      get :tujuan_renja_opd
      get :sasaran_renja_opd
      get :program_renja_opd
      get :kegiatan_renja_opd
      get :subkegiatan_renja_opd
      get :iku_opd
      get :iku_sakip
      get :cetak_iku_opd
      get :lppd_outcome
      get :lppd_output
      get :spm_outcome
      get :spm_output
      get :sdgs_outcome
      get :sdgs_output
      get :rb_outcome
      get :rb_output
      get :stunting_outcome
      get :stunting_output
      get :penanganan_tb_outcome
      get :penanganan_tb_output

      get :new_target_iku_sasaran
    end

    member do
      get :edit_target_iku
      patch :update_iku
      patch :update_realisasi
      delete :hide_iku
      delete :hide_iku_indikator_sasaran
      delete :hide_iku_sasaran
      get :edit_keterangan
      patch :update_keterangan
    end
  end
  resources :pindah_pohon_kinerjas, only: %i[show edit update]
  resources :permasalahan_opds
  resources :strategi_arah_kebijakans do
    collection do
      get :opd
    end
  end
  resources :jabatans do
    resources :kepegawaians do
      collection do
        get :edit_jumlah
        post :update_jumlah
      end
    end
  end
  resources :status_tombols
  resources :external_urls
  resources :reviews
  resources :kriteria
  resources :sub_kriteria
  resources :pelaksana do
    member do
      get :teman
      get :edit_role_tim
      post :update_role_tim
    end
    collection do
      patch :toggle_inovator
    end
  end
  resources :crosscuttings do
    member do
      get :edit_keterangan
      post :update_keterangan
    end
    collection do
      get :internal
      get :external
      get :external_pemerintah
      get :external_non_pemerintah
    end
  end
  resources :pohon_kinerja_opds do
    member do
      get :new_child
    end
    collection do
      get :cascading
    end
  end
  resources :tims
  # TODO: Refactor controller to resources
  resources :pohon_tematik do
    member do
      get :new_sub
      get :edit_sub_tematik
      get :pindah_sub_tematik
      patch :update_sub_tematik
      get :new_opd_tematik
      get :edit_opd_tematik
      patch :update_opd_tematik
      get :pindah_opd_tematik
      get :new_strategi_tematik
      get :new_strategi
      get :edit_strategi
      patch :update_strategi
      get :new_tactical_tematik
      get :new_tactical
      get :edit_tactical
      patch :update_tactical
      get :new_operational_tematik
      get :new_operational
      get :edit_operational
      patch :update_operational
      patch :pindah_pohon
      patch :terima
      get :tolak_strategi
      patch :tolak
      get :new_sub_sub
      get :edit_sub_sub
      patch :toggle_is_active
    end
    collection do
      post :create_sub_tema
      post :create_opd_tematik
      post :create_strategi_tematik
      post :create_strategi_tematik_baru
      post :create_tactical_tematik
      post :create_tactical_tematik_baru
      post :create_operational_tematik
      post :create_operational_tematik_baru
      post :create_sub_sub_tema
      get :filter
      get :get_tematik_opd
    end
  end
  resources :tematiks do
    collection do
      get :list_tematik_kota
      get :sub_tematiks
      post :sub
      get :new_sub
    end

    member do
      get :edit_sub
      post :sub
      get :rad_cetak
      patch :update_sub
      delete :sub
    end
  end
  resources :sub_sub_tematiks, only: %i[create update]
  resources :subdomains
  resources :opd_bidangs
  resources :periodes
  resources :tahuns
  resources :domains
  resources :kebutuhans
  resources :komentars do
    collection do
      get :komentar_pokin
    end
  end
  resources :spbe_rincians
  resources :spbes do
    collection do
      get :index_opd
      get :custom_tanggal_cetak
      get :cetak
      get :cetak_kota
    end
    member do
      get :edit_operational_opd
    end
  end
  resources :pagu_anggarans do
    get :new_batasan, on: :collection
    post :create_batasan, on: :collection
    get :edit_serapan, on: :collection
    post :simpan_serapan, on: :collection
    member do
      get :edit_batasan
      patch :update_batasan
    end
  end
  resources :indikator_sasarans do
    resources :manual_iks do
      member do
        get :overview
      end
    end
  end
  resources :sasaran_opds
  resources :tujuan_opds do
    collection do
      post :admin_filter
    end
  end
  resources :pohon_kinerja do
    member do
      get :transfer_pohon
      post :transfer
      get :panggil_teman
      post :simpan_teman
      get :daftar_temans
      get :daftar_strategi
      post :pasangkan
      get :daftar_linked_strategi
      post :set_clone
      get :pindah
      get :list_dibagikan
      get :new_tactical
      get :new_operational
    end
    collection do
      get :kota
      get :cascading
      get :opd
      get :asn
      post :admin_filter
      get :print
      get :excel_kota
      get :pdf_pokin_kota
      get :pdf_cascading_kota
      get :pdf_pokin_opd
      get :pdf_cascading_opd
      get :excel_opd
      get :rekap
      post :filter_rekap
      get :rekap_opd
      post :filter_rekap_opd
      get :clone_list_opd
      post :clone_pokin_opd
      post :clone_pokin_isu_strategis_opd
      post :clone_pokin_kota
      get :review_opd
      get :review_kota
      get :manual
      get :clone
      get :new_strategic
      get :list_pohon
    end
  end
  resources :strategi_opds
  resources :strategi_kota do
    member do
      get :bagikan_ke_opd
      post :pilih_opd
      get :list_strategi_opd
      post :hapus_bagikan_ke_opd
    end
  end
  resources :strategis do
    member do
      get :bagikan_pokin
      post :pilih_asn
      get :list_strategi_asn
      post :hapus_bagikan_ke_asn
      get :ganti_nip
      get :renaksi
    end
    collection do
      get :rekap_strategi
      get :pokin_list
    end
  end
  resources :isu_strategis_opds do
    collection do
      post :admin_filter
    end
    member do
      get :clone
    end
  end
  resources :isu_strategis_kota do
    member do
      get :list_strategi_kota
    end
  end
  # get "/gender", to: "genders#gender"
  # get "/gap_gender", to: "genders#gap_gender"
  # get "/laporan_gender", to: "genders#laporan_gender"
  # get "/pdf_gender/:id/:tahun", to: "genders#pdf_gender"
  resources :genders do
    collection do
      get :gender
      get :gap
      get :gbs
      get :laporan_gender
      get :laporan_gap
      get :laporan_gbs
      # get "pdf_gender/:id/:tahun", to: "genders#pdf_gender"
      # get "pdf_gap_gender/:id/:tahun", to: "genders#pdf_gap_gender"
    end

    member do
      get :pdf_gbs
      get :pdf_gap
      get :admin_edit
    end
  end
  resources :tujuans
  # get 'isu_dan_permasalahans/index'
  resources :renstra do
    collection do
      get :admin_renstra
      get :laporan
      get :renstra_cetak
      get :edit_indikator
      post :update_indikator
    end
    member do
      post :update_programs
      get :edit_realisasi
    end
  end

  resources :isu_dan_permasalahans, param: :kode_program do
    member do
      get :add_new
      post :add_isu_strategis
    end
  end

app/helpers/pohon_kinerja_opds_helper.rb
module PohonKinerjaOpdsHelper
  def child_strategi(parent, childs)
    childs.select { |str| str.pohon_ref_id.to_i == parent.id }
  rescue NoMethodError
    []
  end

  def childs(pohon_kinerja_opd)
    case pohon_kinerja_opd.role
    when 'eselon_2'
      child_strategi(pohon_kinerja_opd, @tactical_opd)
    when 'strategi_pohon_kota'
      child_strategi(pohon_kinerja_opd, @tactical_kota)
    when 'eselon_3'
      child_strategi(pohon_kinerja_opd, @operational_opd)
    when 'tactical_pohon_kota'
      child_strategi(pohon_kinerja_opd, @operational_kota)
    else
      child_strategi(pohon_kinerja_opd, @staff_opd)
    end
  end

  def anggaran_pohon(sasaran, role)
    strategi = case role
               when 'pohon_kota'
                 AnggaranPohon::Tematik.new(sasaran, @tahun)
               when 'sub_pohon_kota'
                 AnggaranPohon::SubTematik.new(sasaran, @tahun)
               when 'sub_sub_pohon_kota'
                 AnggaranPohon::SubSubTematik.new(sasaran, @tahun)
               when 'eselon_2'
                 AnggaranPohon::Strategic.new(sasaran)
               when 'eselon_3'
                 AnggaranPohon::Tactical.new(sasaran)
               else
                 AnggaranPohon::Operational.new(sasaran)
               end
    anggaran = AnggaranSasaran.new(strategi)
    anggaran.anggaran
  end

  def pagu_pohon(sasaran, role)
    strategi = case role
               when 'pohon_kota'
                 AnggaranPohon::Tematik.new(sasaran, @tahun)
               when 'sub_pohon_kota'
                 AnggaranPohon::SubTematik.new(sasaran, @tahun)
               when 'sub_sub_pohon_kota'
                 AnggaranPohon::SubSubTematik.new(sasaran, @tahun)
               when 'eselon_2'
                 AnggaranPohon::Strategic.new(sasaran)
               when 'eselon_3'
                 AnggaranPohon::Tactical.new(sasaran)
               else
                 AnggaranPohon::Operational.new(sasaran)
               end
    anggaran = AnggaranSasaran.new(strategi)
    number_with_delimiter(anggaran.anggaran)
  end

  def program_pohon(sasaran, role)
    strategi = case role
               when 'pohon_kota'
                 AnggaranPohon::Tematik.new(sasaran, @tahun)
               when 'sub_pohon_kota'
                 AnggaranPohon::SubTematik.new(sasaran, @tahun)
               when 'sub_sub_pohon_kota'
                 AnggaranPohon::SubSubTematik.new(sasaran, @tahun)
               when 'eselon_2'
                 AnggaranPohon::Strategic.new(sasaran)
               when 'eselon_3'
                 AnggaranPohon::Tactical.new(sasaran)
               when 'eselon_4'
                 AnggaranPohon::Operational.new(sasaran)
               end
    context = AnggaranSasaran.new(strategi)
    context.programs.reject { |prg| prg.nama_program =~ /PROGRAM PENUNJANG/ }
  end
end

app/views/pohon_kinerja_opds/_childs.html.erb
<ul class='d-none' id='<%= id %>'>
    <%= render partial: partial, collection: childs %>
</ul>

app/views/pohon_kinerja_opds/_form.html.erb
<%= form_with(url: url, model: model,
              method: method, local: false,
              data: {
                  controller: 'pohon-tematik',
                  action: 'ajax:success->pohon-tematik#ajaxSuccess'
              }) do |form| %>
  <div class="field">
    <%= form.hidden_field :role, class: "form-control" %>
    <%= form.hidden_field :strategi_ref_id, class: "form-control" %>
  </div>
  <div class="field">
    <%= form.label :strategi, class: "form-label" %>
    <%= form.text_field :strategi, class: "form-control" %>
  </div>
  <% if model.new_record? %>
    <%= form.hidden_field :role, class: "form-control" %>
    <%= form.hidden_field :opd_id, class: "form-control" %>
    <%= form.hidden_field :strategi_ref_id, class: "form-control" %>
  <% end %>
  <div class="field" id="indikator-pohon">
    <%= form.fields_for :indikators do |indikator_form| %>
      <%= render 'indikators/indikator_fields', form: indikator_form %>
    <% end %>
  </div>
  <%= link_to_add_nested(form, :indikators, '#indikator-pohon',
                          link_classes: 'btn btn-outline-primary btn-sm',
                          link_text: 'Tambah Indikator',
                          partial: 'indikators/indikator_fields') %>
  <div class="field">
    <%= form.label :keterangan, class: 'form-label' %>
    <%= form.text_field :keterangan, class: 'form-control', required: true, id: "pohon_keterangan_#{form.object_id.to_s}" %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pohon_kinerja_opds/_form_child.html.erb
<%= form_with(url: url, model: model,
              method: method, local: false,
              data: {
                  controller: 'pohon-tematik',
                  action: 'ajax:success->pohon-tematik#ajaxSuccess'
              }) do |form| %>
  <div class="field">
    <%= form.hidden_field :role, class: "form-control" %>
    <%= form.hidden_field :strategi_ref_id, class: "form-control" %>
  </div>
  <div class="field">
    <%= form.label :strategi, class: "form-label" %>
    <%= form.text_field :strategi, class: "form-control" %>
  </div>
  <% if model.new_record? %>
    <%= form.hidden_field :role, class: "form-control" %>
    <%= form.hidden_field :opd_id, class: "form-control" %>
    <%= form.hidden_field :strategi_ref_id, class: "form-control" %>
  <% end %>
  <div class="field" id="indikator-pohon">
    <%= form.fields_for :indikators do |indikator_form| %>
      <%= render 'indikators/indikator_fields', form: indikator_form %>
    <% end %>
  </div>
  <%= link_to_add_nested(form, :indikators, '#indikator-pohon',
                          link_classes: 'btn btn-outline-primary btn-sm',
                          link_text: 'Tambah Indikator',
                          partial: 'indikators/indikator_fields') %>
  <div class="field">
    <%= form.label :keterangan, class: 'form-label' %>
    <%= form.text_field :keterangan, class: 'form-control', required: true, id: "pohon_keterangan_#{form.object_id.to_s}" %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pohon_kinerja_opds/_item_cascading_inovasi.html.erb
<% if pohon.child_inovasi.any? %>
  <div class="pohon-body">
    <table class="table table-bordered table-success">
      <tr>
        <td class="text-start fw-bolder">Jumlah Inovasi</td>
        <td class="text-center fw-bolder">
          <%= pohon.child_inovasi.size %>
        </td>
      </tr>
    </table>
  </div>
<% end %>

app/views/pohon_kinerja_opds/_item_cascading_tombol.html.erb
<% unless pohon.exists? && !reviewer? %>
  <% if pohon.real.instance_of?(StrategiPohon) %>
    <% if privileged_user || current_user.eselon_user == pohon.role_atasan || current_user.eselon_user == pohon.role %>
      <div class="pohon-tombol mb-3">
        <div class="row">
          <div class="col">
            <%= link_to new_crosscutting_path(strategi_id: pohon, partial: partial),
                        remote: true,
                        class: 'btn btn-sm btn-outline-gray-900',
                        data: {
                          controller: 'form-modal',
                          action: 'form-modal#appendForm',
                          form_modal_location_param: 'form-crosscutting-body',
                          bs_target: '#form-crosscutting',
                          bs_toggle: 'modal'
                        },
                        style: 'font-size: 0.8em;' do %>
              <span class="fas fa-link me-2"></span>
              <span>Crosscutting</span>
            <% end %>
          </div>
          <div class="col">
            <%= link_to pelaksana_path(pohon),
                        remote: true,
                        class: 'btn btn-sm btn-outline-gray-900',
                        data: {
                          controller: 'form-modal',
                          action: 'form-modal#appendForm',
                          form_modal_location_param: 'form-pelaksana-body',
                          bs_target: '#form-pelaksana',
                          bs_toggle: 'modal'
                        } do %>
              <span class="fas fa-user-plus me-2"></span>
              <span>Pelaksana</span>
            <% end %>
          </div>
          <div class="col">
            <%= link_to new_indikators_user_path(role: pohon.role, dom_id: dom_id(pohon.real), strategi_id: pohon.real.id),
                        remote: true,
                        class: 'btn btn-sm btn-outline-success',
                        data: {
                          controller: 'form-modal',
                          action: 'form-modal#appendForm',
                          form_modal_location_param: 'form-indikator-pelaksana-body',
                          bs_target: '#form-indikator-pelaksana',
                          bs_toggle: 'modal'
                        } do %>
              <span class="fas fa-crosshairs me-2"></span>
              <span>Indikator</span>
            <% end %>
          </div>
          <div class="col">
            <%= link_to edit_pohon_kinerja_opd_path(pohon, partial: 'item_cascading'),
                        remote: true,
                        class: 'btn btn-sm btn-outline-info',
                        data: {
                          controller: 'pohon-tematik',
                          action: 'ajax:complete->pohon-tematik#pindahPohon:prevent'
                        } do %>
              <i class="fas fa-edit me-2"></i>
              <span>Edit</span>
            <% end %>
          </div>
          <div class="col">
            <%= link_to pohon_kinerja_opd_path(pohon),
                        remote: true,
                        method: :delete,
                        class: 'btn btn-sm btn-outline-danger',
                        data: {
                          confirm_swal: 'Hapus pohon kinerja?',
                          action: 'ajax:success->pohon-tematik#ajaxDelete'
                        } do %>
              <i class="fas fa-trash me-2"></i>
              <span>Hapus</span>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <% unless pohon.processed? %>
      <% unless pohon.parent_tematik_aktif?(pohon.real) %>
        <div class="pohon-tombol mb-3">
          <div class="row">
            <div class="col">
              <%= link_to terima_pohon_tematik_path(pohon, partial: 'pohon_kinerja_opds/pohon_cascading'),
                          remote: true,
                          method: :patch,
                          class: 'btn btn-outline-success',
                          data: {
                            confirm_swal: "Terima strategi ?",
                            method: 'PATCH',
                            controller: 'pohon-tematik',
                            action: 'ajax:complete->pohon-tematik#terimaPohon:prevent'
                          } do %>
                <i class="fas fa-check me-2"></i>
                <span>Terima</span>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="pohon-tombol mb-3">
        <div class="row">
          <div class="col">
            <button class='btn btn-outline-primary'
                    data-action="pohon-tematik#scrollTo"
                    data-pohon-tematik-strategi-param="<%= pohon.pohonable.id %>" >
              <i class="fas fa-arrow-right me-2"></i>
              <span>Cek Strategi</span>
            </button>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/pohon_kinerja_opds/_item_indikators.html.erb
<div class="pohon-body">
  <% pohon.pelaksana.each.with_index(1) do |dibagikan, no| %>
    <% indikator_pelaksanas = dibagikan.user.indikators.by_strategi_id(pohon.real.id) %>
    <% if indikator_pelaksanas.any? %>
      <table class="table table-bordered mb-3">
        <tr>
          <td class="text-start" width="20px">Pelaksana</td>
          <td class="text-wrap text-start"><%= dibagikan.user %></td>
        </tr>
        <% indikator_pelaksanas.each.with_index(1) do |ind, no_i| %>
          <tr>
            <td class="text-start" width="20px">Indikator
              <%= ind.jenis %>
              <%= ind.sub_jenis %>
              <%= no_i %>
            </td>
            <td class="text-wrap text-start"><%= ind %></td>
          </tr>
        <% end %>
      </table>
    <% end %>
  <% end %>
</div>

app/views/pohon_kinerja_opds/_item_opd.html.erb
<% show_button = local_assigns.fetch(:show_button, true) %>
<div class="tf-nc" style="width: 450px;">
  <div class="pohon">
    <div class="pohon-title">
      <h5 class="text-center"><strong><%= title %> OPD</strong></h5>
      <% unless guest? %>
        <% if privileged_user && show_button %>
          <%= link_to opd_clone_path(@opd), remote: true,
                      data: {
                        controller: 'form-modal',
                        action: 'form-modal#appendForm',
                        form_modal_location_param: 'form-modal-body',
                        bs_toggle: 'modal',
                        bs_target: '#form-modal'
                      },
                      class: "btn btn-sm btn-primary w-100 mt-3" do %>
            <i class="fa fa-clone me-2"></i>
            <span>Clone</span>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="pohon-body">
      <table class="table table-bordered">
        <tr>
          <td class="text-start" width="30px">Nama OPD</td>
          <td class="text-wrap text-start fw-bolder"><%= @nama_opd %></td>
        </tr>
        <% unless @tahun.nil? %>
          <% size_tujuan = @tujuan_opds.size %>
          <% @tujuan_opds.each.with_index(1) do |tujuan, no| %>
            <tr>
              <td class="text-start" width="30px">Tujuan <%= size_tujuan > 1  ? no : ''  %></td>
              <td class="text-wrap text-start"><%= tujuan %></td>
            </tr>
            <% tujuan.indikators.each do |indikator_tujuan|  %>
              <tr>
                <td class="text-start" width="30px">Indikator</td>
                <td class="text-wrap text-start"  ><%= indikator_tujuan || '-' %></td>
              </tr>
              <tr>
                <% target = indikator_tujuan.targets.find_by(tahun: @tahun_asli) %>
                <td class="text-start" width="30px">Target</td>
                <td class="text-wrap text-start"  ><%= target&.target_satuan %></td>
              </tr>
            <% end %>
          <% end %>
        <% end %>
        <tr>
          <td class="text-start" width="30px">Tahun</td>
          <td class="text-wrap text-start"><%= @tahun %></td>
        </tr>
      </table>
    </div>
    <div class="pohon-foot">
      <div class="row">
        <div class="col">
          <button type="button" class="btn btn-primary w-100" data-action="pohon-tematik#toggleAll" data-pohon-tematik-show-param="false">Tampilkan Semua</button>
        </div>
        <div class="col">
          <% show_button = local_assigns.fetch(:show_button, true) %>
          <% unless guest? %>
            <% if privileged_user && show_button %>
              <%= link_to new_pohon_kinerja_opd_path(partial: partial),
                          remote: true,
                          class: 'btn btn-outline-success align-items-center w-100',
                          data: {
                            controller: 'pohon-tematik',
                            action: 'ajax:complete->pohon-tematik#addStrategiTematik:prevent',
                          } do %>
                <i class="fas fa-plus me-2"></i>
                <span>Strategi Baru</span>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pohon_kinerja_opds/_item_pohon.html.erb
<% presenter = PohonKinerjaPresenter.new(pohon) %>
<% show_button = local_assigns.fetch(:show_button, true) %>
<div class="pohon">
  <%= render partial: 'pohon_kinerja_opds/item_pohon_title', locals: { pohon: presenter, show_button: show_button } %>
  <% if pohon.role == 'eselon_2' %>
    <%= link_to pdf_pokin_opd_pohon_kinerja_index_path(strategic_id: pohon.id),
                class: "btn btn-tertiary w-100 mt-3",
                target: "blank" do %>
      <i class="fa fa-file-image"></i>
      <span>Cetak Pohon Kinerja</span>
    <% end %>
  <% end %>
  <%= render partial: 'pohon_kinerja_opds/item_pohon_body', locals: { pohon: presenter, show_button: show_button } %>
  <%= render partial: 'pohon_kinerja_opds/item_pohon_crosscutting', locals: { pohon: presenter, show_button: show_button } %>
  <%= render partial: 'pohon_kinerja_opds/item_reviews', locals: { pohon: presenter, show_button: show_button } %>
  <% unless guest? %>
    <% if show_button %>
      <%= render partial: 'pohon_kinerja_opds/item_pohon_tombol', locals: { pohon: presenter, show_button: show_button, partial: 'item_pohon' } %>
    <% end %>
  <% end %>
  <%= render partial: 'pohon_kinerja_opds/item_pohon_foot', locals: { pohon: presenter, partial: 'pohon_kinerja_opd', show_button: show_button } %>
</div>

app/views/pohon_kinerja_opds/_item_pohon_title.html.erb
<div class="pohon-title <%= pohon.status %>" id="<%= pohon.pohon_kota_id %>">
  <% if pohon.type == 'Pohon' %>
    <% if pohon.parent_tematik_aktif?(pohon.real) %>
      <h5 class="text-center bg-danger border border-3 border-primary p-2 mb-2"><strong>Non-Aktif</strong></h5>
    <% end %>
  <% end %>
  <h5 class="text-center"><strong><%= pohon.title_up %> <%= pohon.pohon_kota %></strong></h5>
</div>

app/views/pohon_kinerja_opds/new_child.html.erb
<li class="<%= dom_class(@pohon) %>">
  <div class="tf-nc" style="width: 450px;">
    <div class="pohon-title">
      <h5 class="text-center"><strong><%= @title %> Baru</strong></h5>
    </div>
    <div class="pohon-body">
      <%= render 'form',  { model: @pohon, url: pohon_kinerja_opds_path(partial: @partial), method: :post } %>
    </div>
    <div class="pohon-foot">
      <button type="button" class="btn btn-danger w-100" data-action="pohon-tematik#closeForm">Batal</button>
    </div>
  </div>
</li>