config/routes.rb
# frozen_string_literal: true

# == Route Map
#

# require 'resque/server'
require "sidekiq/web"
require "sidekiq_unique_jobs/web"

Rails.application.routes.draw do
  resources :tte_documents do
    member do
      get :status
      get :download
    end
  end
  resources :bpmn_spbes do
    member do
      get :tambah_catatan
      patch :simpan_catatan
      get :upload_file
      get :upload_file_laporan
    end
    collection do
      get :pilih
      get :filter_rekap
    end
  end
  resources :rencana_aksi_opds do
    collection do
      get :cetak
      get :filter_rekapitulasi
      get :cetak_rekapitulasi
      get :jumlah_rekapitulasi
      get :jumlah_perintah_walikota
      get :cetak_rekap_jumlah
      get :cetak_jumlah_perintah_walikota
    end
    member do
      patch :toggle_sasarans_is_perintah_walikota
    end
  end
  resources :program_unggulans do
    collection do
      get :asta_karya
      get :filter
      get :asta_cita
      get :filter_asta_cita
      get :nawa_bhakti
      get :filter_nawa_bhakti
    end
  end
  resources :kolabs do
    collection do
      get :opd_kolaborator
    end
  end
  resources :misis, path: "misi_kota" do
    collection do
      get :lists
    end
  end
  resources :visis, path: "visi_kota"
  resources :manrisks do
    collection do
      get :filter
      get :konteks_strategis
      get :identifikasi_strategis
      get :filter_identifikasi_strategis
    end
    member do
      get :filter_konteks_strategis
      get :edit_konteks_strategis
      post :simpan_konteks_strategis
    end
  end
  resources :realisasis
  resources :inovasi_masyarakats
  resources :anggota_tims
  resources :inovasi_tims do
    collection do
      get :new_internal
      get :new_non_pemerintah
    end
  end
  resources :mitras do
    collection do
      get :new_internal
      get :new_external_pemerintah
      get :new_external_non_pemerintah
      get :new_external_non_pemerintah_ogp
    end
  end
  resources :akar_masalahs do
    member do
      post :pilih_masalah
    end
  end
  resources :tim_kerja, only: [] do
    member do
      get :edit_dasar_hukum
      post :update_dasar_hukum
      delete :hapus_dasar_hukum
      get :edit_rincian_tugas
      post :update_rincian_tugas
      delete :hapus_rincian_tugas
    end
  end
  resources :kuncis
  resources :anggaran_sbks
  resources :asets
  resources :jenis_jabatans
  resources :jumlahs
  resources :data_dukungs
  resources :indikators_users do
    collection do
      get :indikator_by_jenis
      get :pelaksana_indikator
    end
  end
  resources :indikators do
    collection do
      post :import
      get :rpjp_makro
      get :rpjp_opd
      get :rpjmd_makro
      get :rkpd_makro
      get :rkpd_tujuan
      get :rkpd_sasaran
      get :rkpd_program
      get :iku_kota
      get :renja_opd
      post :item_renja_opd
      get :tujuan_renja_opd
      get :sasaran_renja_opd
      get :program_renja_opd
      get :kegiatan_renja_opd
      get :subkegiatan_renja_opd
      get :iku_opd
      get :iku_sakip
      get :cetak_iku_opd
      get :lppd_outcome
      get :lppd_output
      get :spm_outcome
      get :spm_output
      get :sdgs_outcome
      get :sdgs_output
      get :rb_outcome
      get :rb_output
      get :stunting_outcome
      get :stunting_output
      get :penanganan_tb_outcome
      get :penanganan_tb_output

      get :new_target_iku_sasaran
    end

    member do
      get :edit_target_iku
      patch :update_iku
      patch :update_realisasi
      delete :hide_iku
      delete :hide_iku_indikator_sasaran
      delete :hide_iku_sasaran
      get :edit_keterangan
      patch :update_keterangan
    end
  end
  resources :pindah_pohon_kinerjas, only: %i[show edit update]
  resources :permasalahan_opds
  resources :strategi_arah_kebijakans do
    collection do
      get :opd
    end
  end
  resources :jabatans do
    resources :kepegawaians do
      collection do
        get :edit_jumlah
        post :update_jumlah
      end
    end
  end
  resources :status_tombols
  resources :external_urls
  resources :reviews
  resources :kriteria
  resources :sub_kriteria
  resources :pelaksana do
    member do
      get :teman
      get :edit_role_tim
      post :update_role_tim
    end
    collection do
      patch :toggle_inovator
    end
  end
  resources :crosscuttings do
    member do
      get :edit_keterangan
      post :update_keterangan
    end
    collection do
      get :internal
      get :external
      get :external_pemerintah
      get :external_non_pemerintah
    end
  end
  resources :pohon_kinerja_opds do
    member do
      get :new_child
    end
    collection do
      get :cascading
    end
  end
  resources :tims
  # TODO: Refactor controller to resources
  resources :pohon_tematik do
    member do
      get :new_sub
      get :edit_sub_tematik
      get :pindah_sub_tematik
      patch :update_sub_tematik
      get :new_opd_tematik
      get :edit_opd_tematik
      patch :update_opd_tematik
      get :pindah_opd_tematik
      get :new_strategi_tematik
      get :new_strategi
      get :edit_strategi
      patch :update_strategi
      get :new_tactical_tematik
      get :new_tactical
      get :edit_tactical
      patch :update_tactical
      get :new_operational_tematik
      get :new_operational
      get :edit_operational
      patch :update_operational
      patch :pindah_pohon
      patch :terima
      get :tolak_strategi
      patch :tolak
      get :new_sub_sub
      get :edit_sub_sub
      patch :toggle_is_active
    end
    collection do
      post :create_sub_tema
      post :create_opd_tematik
      post :create_strategi_tematik
      post :create_strategi_tematik_baru
      post :create_tactical_tematik
      post :create_tactical_tematik_baru
      post :create_operational_tematik
      post :create_operational_tematik_baru
      post :create_sub_sub_tema
      get :filter
      get :get_tematik_opd
    end
  end
  resources :tematiks do
    collection do
      get :list_tematik_kota
      get :sub_tematiks
      post :sub
      get :new_sub
    end

    member do
      get :edit_sub
      post :sub
      get :rad_cetak
      patch :update_sub
      delete :sub
    end
  end
  resources :sub_sub_tematiks, only: %i[create update]
  resources :subdomains
  resources :opd_bidangs
  resources :periodes
  resources :tahuns
  resources :domains
  resources :kebutuhans
  resources :komentars do
    collection do
      get :komentar_pokin
    end
  end
  resources :spbe_rincians
  resources :spbes do
    collection do
      get :index_opd
      get :custom_tanggal_cetak
      get :cetak
      get :cetak_kota
    end
    member do
      get :edit_operational_opd
    end
  end
  resources :pagu_anggarans do
    get :new_batasan, on: :collection
    post :create_batasan, on: :collection
    get :edit_serapan, on: :collection
    post :simpan_serapan, on: :collection
    member do
      get :edit_batasan
      patch :update_batasan
    end
  end
  resources :indikator_sasarans do
    resources :manual_iks do
      member do
        get :overview
      end
    end
  end
  resources :sasaran_opds
  resources :tujuan_opds do
    collection do
      post :admin_filter
    end
  end
  resources :pohon_kinerja do
    member do
      get :transfer_pohon
      post :transfer
      get :panggil_teman
      post :simpan_teman
      get :daftar_temans
      get :daftar_strategi
      post :pasangkan
      get :daftar_linked_strategi
      post :set_clone
      get :pindah
      get :list_dibagikan
      get :new_tactical
      get :new_operational
    end
    collection do
      get :kota
      get :cascading
      get :opd
      get :asn
      post :admin_filter
      get :print
      get :excel_kota
      get :pdf_pokin_kota
      get :pdf_cascading_kota
      get :pdf_pokin_opd
      get :pdf_cascading_opd
      get :excel_opd
      get :rekap
      post :filter_rekap
      get :rekap_opd
      post :filter_rekap_opd
      get :clone_list_opd
      post :clone_pokin_opd
      post :clone_pokin_isu_strategis_opd
      post :clone_pokin_kota
      get :review_opd
      get :review_kota
      get :manual
      get :clone
      get :new_strategic
      get :list_pohon
    end
  end
  resources :strategi_opds
  resources :strategi_kota do
    member do
      get :bagikan_ke_opd
      post :pilih_opd
      get :list_strategi_opd
      post :hapus_bagikan_ke_opd
    end
  end
  resources :strategis do
    member do
      get :bagikan_pokin
      post :pilih_asn
      get :list_strategi_asn
      post :hapus_bagikan_ke_asn
      get :ganti_nip
      get :renaksi
    end
    collection do
      get :rekap_strategi
      get :pokin_list
    end
  end
  resources :isu_strategis_opds do
    collection do
      post :admin_filter
    end
    member do
      get :clone
    end
  end
  resources :isu_strategis_kota do
    member do
      get :list_strategi_kota
    end
  end
  # get "/gender", to: "genders#gender"
  # get "/gap_gender", to: "genders#gap_gender"
  # get "/laporan_gender", to: "genders#laporan_gender"
  # get "/pdf_gender/:id/:tahun", to: "genders#pdf_gender"
  resources :genders do
    collection do
      get :gender
      get :gap
      get :gbs
      get :laporan_gender
      get :laporan_gap
      get :laporan_gbs
      # get "pdf_gender/:id/:tahun", to: "genders#pdf_gender"
      # get "pdf_gap_gender/:id/:tahun", to: "genders#pdf_gap_gender"
    end

    member do
      get :pdf_gbs
      get :pdf_gap
      get :admin_edit
    end
  end
  resources :tujuans
  # get 'isu_dan_permasalahans/index'
  resources :renstra do
    collection do
      get :admin_renstra
      get :laporan
      get :renstra_cetak
      get :edit_indikator
      post :update_indikator
    end
    member do
      post :update_programs
      get :edit_realisasi
    end
  end

  resources :isu_dan_permasalahans, param: :kode_program do
    member do
      get :add_new
      post :add_isu_strategis
    end
  end

app/models/visi.rb
# == Schema Information
#
# Table name: visis
#
#  id          :bigint           not null, primary key
#  keterangan  :string
#  tahun_akhir :string
#  tahun_awal  :string
#  urutan      :integer          default(1)
#  visi        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  lembaga_id  :bigint           not null
#
# Indexes
#
#  index_visis_on_lembaga_id  (lembaga_id)
#
# Foreign Keys
#
#  fk_rails_...  (lembaga_id => lembagas.id)
#
class Visi < ApplicationRecord
  has_many :misis
  belongs_to :lembaga

  validates :visi, presence: true, length: { minimum: 5 }
  validates :urutan, numericality: { only_integer: true }
  validates :tahun_awal, presence: true, length: { is: 4 }
  validates :tahun_akhir, presence: true, length: { is: 4 }

  scope :by_periode, lambda { |tahun|
                       where("tahun_awal::integer <= ?::integer", tahun)
                         .where("tahun_akhir::integer >= ?::integer", tahun)
                     }

  def to_s
    visi
  end

  def visi_with_urutan_and_lembaga
    "#{urutan}. #{visi} - #{lembaga}"
  end

  def periode
    "#{tahun_awal}-#{tahun_akhir}"
  end
end

app/controllers/visis_controller.rb
class VisisController < ApplicationController
  before_action :set_visi, only: %i[show edit update destroy]
  before_action :set_periode_lembaga, only: %i[index new]
  layout false, only: %i[new edit]

  # GET /visis or /visis.json
  def index
    selected_id = params[:selected]

    @visis = if selected_id.present? && request.format.json?
               Visi.where(tahun_awal: @tahun_awal, tahun_akhir: @tahun_akhir,
                          lembaga_id: @lembaga_id, id: selected_id)
             else
               Visi.where(tahun_awal: @tahun_awal, tahun_akhir: @tahun_akhir,
                          lembaga_id: @lembaga_id)
             end
  end

  # GET /visis/1 or /visis/1.json
  def show; end

  # GET /visis/new
  def new
    lembaga = Lembaga.find(cookies[:lembaga_id])
    @visi = Visi.new(lembaga_id: lembaga.id)
  end

  # GET /visis/1/edit
  def edit
    @periode = Periode.find_by(tahun_awal: @visi.tahun_awal,
                               tahun_akhir: @visi.tahun_akhir)
  end

  # POST /visis or /visis.json
  def create
    @visi = Visi.new(visi_params)

    if @visi.save
      render json: { resText: 'Visi ditambahkan',
                     html_content: html_content({ visi: @visi },
                                                partial: 'visis/visi') }
        .to_json,
             status: :ok
    else
      render json: { resText: 'Terjadi kesalahan',
                     html_content: html_content({ visi: @visi },
                                                partial: 'visis/form') }
        .to_json,
             status: :unprocessable_entity
    end
  end

  # PATCH/PUT /visis/1 or /visis/1.json
  def update
    if @visi.update(visi_params)
      render json: { resText: 'Perubahan disimpan',
                     html_content: html_content({ visi: @visi },
                                                partial: 'visis/visi') }
        .to_json,
             status: :ok
    else
      render json: { resText: 'Terjadi kesalahan',
                     html_content: html_content({ visi: @visi },
                                                partial: 'visis/form') }
        .to_json,
             status: :unprocessable_entity
    end
  end

  # DELETE /visis/1 or /visis/1.json
  def destroy
    @visi.destroy

    render json: { resText: "Visi Dihapus" }.to_json, status: :accepted
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_visi
    @visi = Visi.find(params[:id])
  end

  def set_periode_lembaga
    @tahun = cookies[:tahun]
    @lembaga_id = cookies[:lembaga_id]
    @lembaga = cookies[:lembaga]
    return if @tahun.nil?

    tahun_bener = @tahun.match(/murni|perubahan/) ? @tahun[/[^_]\d*/, 0] : @tahun
    @periode = Periode.find_tahun_rpjmd(tahun_bener)

    return if @periode.empty?

    @periode = @periode.first

    @tahun_awal = @periode.tahun_awal
    @tahun_akhir = @periode.tahun_akhir
  end

  # Only allow a list of trusted parameters through.
  def visi_params
    params.require(:visi).permit(:visi, :urutan, :keterangan, :tahun_awal, :tahun_akhir, :lembaga_id)
  end
end

app/helpers/visis_helper.rb
module VisisHelper
end

app/views/visis/_form.html.erb
<%= form_with model: visi, local: false,
              data: {
                controller: 'form-ajax periode',
                form_ajax_target_param: dom_id(visi),
                form_ajax_type_param: visi.new_record? ? 'prepend' : '',
                action: 'ajax:complete->form-ajax#processAjax
                         change-periode@document->periode#fillTahunPeriode'
              } do |form| %>
  <% if visi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visi.errors.count, "error") %> prohibited this visi from being saved:</h2>

      <ul>
        <% visi.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :urutan, class: 'form-label' %>
    <%= form.hidden_field :lembaga_id %>
    <%= form.number_field :urutan, class: 'form-control', min: 1, required: true %>
  </div>

  <div class="field">
    <%= form.label :visi, "Visi Kepala Daerah", class: 'form-label' %>
    <%= form.text_field :visi, class: 'form-control', required: true %>
  </div>

  <div class="field">
    <%= form.label :periode, class: 'form-label' %>
    <%= form.select :periode, [],
     { include_blank: true },
     data: {
       placeholder: 'Periode',
       controller: 'dropdown',
       dropdown_jenis_value: 'extra',
       dropdown_parent_value: '#form-modal',
       dropdown_url_value: '/periodes.json',
       dropdown_jenis_uraian_value: 'RPJMD',
       dropdown_event_name_value: 'change-periode',
       dropdown_selected_value: @periode&.id
     }  %>
  </div>

  <div class="field">
    <%= form.label :tahun_awal, class: 'form-label' %>
    <%= form.text_field :tahun_awal, class: 'form-control',
     required: true, readonly: true, data: { periode_target: 'tahunAwal' } %>
  </div>

  <div class="field">
    <%= form.label :tahun_akhir, class: 'form-label' %>
    <%= form.text_field :tahun_akhir, class: 'form-control',
     required: true, readonly: true, data: { periode_target: 'tahunAkhir' } %>
  </div>

  <div class="field">
    <%= form.label :keterangan, class: 'form-label' %>
    <%= form.text_area :keterangan, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/visis/_visi.html.erb
<tr id="<%= dom_id(visi) %>">
  <td class="text-gray-900" width='20px' scope="row"><%= visi.urutan %></td>
  <td class="text-gray-900 text-wrap" scope="row"><%= visi %></td>
  <td class="text-gray-900" scope="row"><%= visi.periode %></td>
  <td class="text-gray-900 text-wrap" scope="row"><%= visi.keterangan %></td>
  <td class="text-gray-900" scope="row">
    <% unless guest? %>
      <div class="d-grid gap-2">
        <%= render(EditButtonComponent.new(path: edit_visi_path(visi))) %>
        <%= render(DeleteButtonComponent.new(path: visi_path(visi),
                                             title: "Hapus Visi '#{visi}'?" )) %>
      </div>
    <% end %>
  </td>
</tr>

app/views/visis/edit.html.erb
<%= render 'form', visi: @visi %>

app/views/visis/index.html.erb
<%= content_for :html_title, "Visi Kota" %>
<%= content_for :navigation do %>
  <li class="breadcrumb-item" aria-current="page">Perencanaan Kota</li>
  <li class="breadcrumb-item active" aria-current="page">Visi Kota</li>
<% end %>
<% content_for :view_utama do %>
  <% if @periode.present?  %>
    <%= render 'shared/card_layout_subtitle', title: "Visi Kepala Daerah",
               sub_title: @lembaga, sub_title_2: @periode do %>
      <div class="row align-items-center">
        <div class="col"></div>
        <% unless guest? %>
          <div class="col-auto">
            <%= link_to new_visi_path,
                        remote: true,
                        data: {
                          controller: 'form-modal',
                          action: 'ajax:complete->form-modal#success:prevent',
                          bs_toggle: 'modal',
                          bs_target: '#form-modal'
                        },
                        class: 'btn btn-sm btn-primary' do %>
              <i class="fas fa-plus me-2"></i>
              <span>Tambah Visi Kepala Daerah</span>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="table-responsive mb-5">
        <table class="table table-bordered align-items-center">
          <thead class="thead-tujuan">
            <tr class="header-tujuan">
              <th class="text-center" width="20px">No.</th>
              <th class="text-center" width="500px">Visi</th>
              <th class="text-center" width="200px">Periode</th>
              <th class="text-center">Keterangan</th>
              <th class="text-center"></th>
            </tr>
          </thead>
          <tbody id="new_visi">
            <%= render partial: 'visis/visi', collection: @visis %>
          </tbody>
        </table>
      </div>
    <% end %>
  <% else %>
    <div class="card border-0 shadow">
      <div class="card-body">
        <p class="alert alert-info">Periode RPJMD tahun <%= @tahun %> belum dibuat</p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/visis/new.html.erb
<%= render 'form', visi: @visi %>

app/views/visis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Visi:</strong>
  <%= @visi.visi %>
</p>

<p>
  <strong>Urutan:</strong>
  <%= @visi.urutan %>
</p>

<p>
  <strong>Keterangan:</strong>
  <%= @visi.keterangan %>
</p>

<p>
  <strong>Tahun awal:</strong>
  <%= @visi.tahun_awal %>
</p>

<p>
  <strong>Tahun akhir:</strong>
  <%= @visi.tahun_akhir %>
</p>

<%= link_to 'Edit', edit_visi_path(@visi) %> |
<%= link_to 'Back', visis_path %>